import { api, downloadExport, getAuthConfig, loginRequest, logoutRequest, setCsrfCookieName } from "./client.js";
import { canRoleWrite, isAdminRole, isOwnerRole, PERMISSION_MATRIX_VERSION } from "./permissions.js";

function byId(id: string): HTMLElement {
  const element = document.getElementById(id);
  if (!element) throw new Error(`missing required element #${id}`);
  return element;
}

function activeView(): HTMLElement {
  const element = document.querySelector<HTMLElement>(".view.active");
  if (!element) throw new Error("missing active view");
  return element;
}

function showError(msg: string){const e=byId('error');e.textContent=msg||'';e.style.display=msg?'block':'none'}
async function guard(fn: () => unknown | Promise<unknown>){try{showError('');await fn()}catch(e){showError(e instanceof Error ? e.message : String(e))}}
function allowedView(id: string){return !(id==='users'||id==='operations')||isAdmin()}
function showView(id: string){if(!allowedView(id))id='dashboard';document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));location.hash=id;loadView(id)}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view || 'dashboard'));
function refreshCurrent(){const id=activeView().id;loadView(id)}
function loadView(id: string){return guard(async()=>{if(id==='dashboard')await loadDashboard();if(id==='opportunities')await loadOpportunities();if(id==='alerts')await loadAlertsWithLifecycle();if(id==='watch')await loadWatch();if(id==='sources')await loadSources();if(id==='observations')await loadObservations();if(id==='users')await loadUsers();if(id==='operations')await loadOperations()})}
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,(c:string)=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"} as Record<string,string>)[c]);
const fmt=(d:any)=>d?String(d).slice(0,16).replace('T',' '):'';
const safeUrl=(u:any)=>/^https?:\/\//i.test(String(u??''))?String(u):null;
declare global { interface HTMLElement { value:any; checked:any } interface Element { dataset:DOMStringMap; onclick:any } }
let currentRole = "VIEWER";
function isAdmin(){return isAdminRole(currentRole)}
function canWrite(){return canRoleWrite(currentRole)}
function isOwner(){return isOwnerRole(currentRole)}
const ADMIN_ACTIONS = new Set(["preview-retention"]);
function applyRoleUi(){
  document.querySelectorAll<HTMLElement>("[data-admin-only=true]").forEach(el=>{el.style.display=isAdmin()?"":"none"});
  document.querySelectorAll<HTMLElement>("[data-write-only=true]").forEach(el=>{el.style.display=canWrite()?"":"none"});
  document.querySelectorAll<HTMLElement>("[data-action]").forEach(el=>{if(ADMIN_ACTIONS.has(el.dataset.action||''))el.style.display=isAdmin()?"":"none"});
  const ownerOption=document.getElementById('newOwnerRole') as HTMLOptionElement|null;if(ownerOption)ownerOption.disabled=!isOwner();
}

async function loadDailyDigest(){let digest:any=null;try{digest=await api('/api/v1/digests/daily')}catch(error){if(!(error instanceof Error&&error.message.startsWith('HTTP 404')))throw error}const meta=byId('digestMeta');const status=byId('digestStatus');const items=byId('digestItems');if(!digest){meta.textContent='';status.textContent='No saved digest for the current workspace';items.innerHTML='<div class="empty">Generate or wait for the scheduled daily snapshot.</div>';return}meta.textContent=`${digest.digest_date} · ${esc(digest.status)} · contract v${esc(digest.contract_version)}`;status.textContent=`${esc(digest.selected_count)} selected / ${esc(digest.total_candidates)} candidates · generated ${fmt(digest.generated_at)}`;items.innerHTML=digest.items?.length?digest.items.map((item:any)=>`<div class="evidence"><div><b>#${esc(item.rank)} ${esc(item.title)}</b> · score ${esc(item.score)} · risk ${esc(item.risk_score)}</div><div class="muted">${esc(item.stage)} · ${esc(item.analysis_status)} · ${esc(item.evidence_provenance)} evidence · ${esc(item.evidence_count)} items</div><div>${esc(item.summary)}</div><div class="muted">${esc((item.selection_reasons||[]).join(' · '))}</div></div>`).join(''):`<div class="empty">No qualifying opportunities for this UTC day.</div>`}
async function loadWeeklyTrends(){let report:any=null;try{report=await api('/api/v1/trends/weekly')}catch(error){if(!(error instanceof Error&&error.message.startsWith('HTTP 404')))throw error}const meta=byId('weeklyTrendMeta');const status=byId('weeklyTrendStatus');const items=byId('weeklyTrendItems');if(!report){meta.textContent='';status.textContent='No saved weekly trend report';items.innerHTML='<div class="empty">Generate or wait for the scheduled weekly snapshot.</div>';return}meta.textContent=`${report.week_start} → ${report.week_end} · baseline ${report.baseline_start} → ${report.baseline_end} · ${esc(report.status)} · contract v${esc(report.contract_version)}`;status.textContent=`${esc(report.selected_count)} selected / ${esc(report.total_candidates)} candidates · generated ${fmt(report.generated_at)}${report.warnings?.length?` · ${esc(report.warnings.join(' · '))}`:''}`;items.innerHTML=report.items?.length?report.items.map((item:any)=>`<div class="evidence"><div><b>#${esc(item.rank)} ${esc(item.keyword)}</b> · ${esc(item.comparison)} · momentum ${esc(item.momentum_score)}</div><div class="muted">${esc(item.current_observations)} current / ${esc(item.baseline_observations)} baseline · Δ ${esc(item.absolute_delta)} · growth ${item.growth_rate===null?'NEW':esc(item.growth_rate)} · ${esc(item.current_sources)} sources · ${esc(item.evidence_provenance)}</div><div class="muted">${esc((item.selection_reasons||[]).join(' · '))}</div><div class="muted">trend ${esc(item.trend_signature)} · last seen ${fmt(item.last_seen_at)}</div></div>`).join(''):`<div class="empty">No qualifying emerging trends for this UTC week.</div>`}
async function loadDashboard(){const d=await api('/api/v1/dashboard');const t=d.totals;const ms=[['Observations',t.observations],['7日证据',t.observations_7d],['Keywords',t.keywords],['Opportunities',t.opportunities],['未读预警',t.unread_alerts],['跟踪机会',t.tracking_opportunities],['收藏机会',t.starred_opportunities],['Active Probes',t.active_probe_tasks],['失败运行 24h',t.failed_collection_runs_24h],['Open Circuits',t.open_source_circuits],['Pending AI',t.pending_external_analysis],['Degraded AI',t.degraded_external_analysis]];byId('metrics').innerHTML=ms.map(x=>`<div class="metric"><strong>${esc(x[1])}</strong><span>${esc(x[0])}</span></div>`).join('');byId('dashOpps').innerHTML=d.top_opportunities.map((x:any)=>`<tr class="clickable" data-action="open-opportunity" data-id="${x.id}"><td>${esc(x.title)}</td><td>${esc(x.stage)}</td><td class="score">${esc(x.score)}</td><td>${esc(x.risk_score)}</td><td>${esc(x.analysis_status)}</td></tr>`).join('');byId('dashKeywords').innerHTML=d.top_keywords.map((x:any)=>`<tr><td>${esc(x.keyword)}</td><td>${esc(x.status)}</td><td class="score">${esc(x.score)}</td><td>${esc(x.sources)}</td></tr>`).join('');await Promise.all([loadDailyDigest(),loadWeeklyTrends()])}

let opportunityCursor: string|null = null;
async function loadOpportunities(append=false){
  const p=new URLSearchParams();const q=byId('oppQ').value.trim();if(q)p.set('q',q);p.set('min_score',byId('oppScore').value||'0');const rs=byId('oppResearch').value;if(rs)p.set('research_status',rs);const star=byId('oppStar').value;if(star)p.set('starred',star);p.set('limit','50');if(append&&opportunityCursor)p.set('cursor',opportunityCursor);
  const d=await api('/api/v1/opportunities/page?'+p);
  const html=d.items.length?d.items.map((x:any)=>`<tr class="clickable" data-action="open-opportunity" data-id="${x.id}"><td>${x.research.starred?'★ ':''}${esc(x.title)}</td><td>${esc(x.stage)}</td><td class="score">${esc(x.score)}</td><td>${esc(x.risk_score)}</td><td>${esc(x.evidence_count)}</td><td>${esc(x.research.status)} P${esc(x.research.priority)}</td><td>${esc((x.summary||'').slice(0,180))}</td></tr>`).join(''):`<tr><td colspan="7" class="empty">暂无匹配机会</td></tr>`;
  if(append&&d.items.length)byId('oppRows').insertAdjacentHTML('beforeend',html);else byId('oppRows').innerHTML=html;
  opportunityCursor=d.next_cursor||null;byId('oppMore').style.display=opportunityCursor?'':'none';
}

async function openOpportunity(id: number){const d=await api(`/api/v1/opportunities/${id}`);byId('drawer').classList.add('open');byId('detailTitle').textContent=d.title;byId('detailMeta').textContent=`${d.stage} · Score ${d.score} · Risk ${d.risk_score} · Evidence ${d.evidence_count}`;const r=d.research;byId('detailBody').innerHTML=`<div class="panel"><h2>研究状态</h2><div class="form-grid"><select id="researchStatus" class="field"><option>NEW</option><option>REVIEWING</option><option>TRACKING</option><option>DISMISSED</option><option>ARCHIVED</option></select><select id="researchPriority" class="field">${[0,1,2,3,4,5].map(v=>`<option value="${v}">P${v}</option>`).join('')}</select><label><input id="researchStar" type="checkbox"> 收藏</label><input id="researchTags" class="field" placeholder="标签，逗号分隔" value="${esc((r.tags||[]).join(','))}"><textarea id="researchNotes" class="field full" placeholder="研究备注">${esc(r.notes||'')}</textarea>${canWrite()?`<button class="btn primary full" data-action="save-research" data-id="${id}">保存研究状态</button>`:`<div class="muted full">只读角色不能修改研究状态</div>`}</div></div><div class="panel"><h2>结构化分析</h2><p><b>摘要</b><br>${esc(d.analysis.summary)}</p><p><b>目标用户</b><br>${esc(d.analysis.target_user)}</p><p><b>商业模式</b><br>${esc(d.analysis.business_model)}</p><p><b>变现</b><br>${esc(d.analysis.monetization)}</p><p><b>风险</b><br>${esc(d.analysis.risk_notes)}</p></div><div class="panel"><h2>关键词</h2>${d.keywords.map((k:any)=>`<span class="tag">${esc(k.keyword)} · ${esc(k.role)}</span>`).join('')}</div><div class="panel"><h2>证据链</h2>${d.evidence.map((e:any)=>`<div class="evidence"><div><b>${esc(e.source)}</b> · ${esc(e.type)} · Q${esc(e.quality)} · ${fmt(e.observed_at)}</div><div>${safeUrl(e.url)?`<a href="${esc(e.url)}" target="_blank" rel="noreferrer">${esc(e.title)}</a>`:esc(e.title)}</div><div class="muted">${esc((e.text||'').slice(0,500))}</div></div>`).join('')||'<div class="empty">暂无证据</div>'}</div>`;byId('researchStatus').value=r.status;byId('researchPriority').value=String(r.priority);byId('researchStar').checked=!!r.starred}
async function openOpportunityWithCitations(id: number){
  const d:any=await api(`/api/v1/opportunities/${id}`);
  const r=d.research;const analysis=d.analysis||{};const evidence=d.evidence||[];const citations=analysis.citations||[];
  const conflict=analysis.conflict||{};
  const evidenceIds=new Set(evidence.map((e:any)=>e.evidence_id));
  const linked=citations.filter((c:any)=>evidenceIds.has(c.evidence_id));
  const citationStatus=linked.length===citations.length?'Citation bindings verified':'Citation binding mismatch';
  const citationHtml=citations.length?citations.map((c:any)=>`<div class="evidence"><div><b>${esc(c.evidence_id)}</b> · ${evidenceIds.has(c.evidence_id)?'matched':'unmatched'}</div><div class="muted">${esc(c.claim)}</div></div>`).join(''):'<div class="empty">No analysis citations</div>';
  const evidenceHtml=evidence.length?evidence.map((e:any)=>`<div class="evidence"><div><b>${esc(e.source)}</b> · ${esc(e.type)} · Q${esc(e.quality)} · ${fmt(e.observed_at)} · rank ${esc(e.citation_rank||'')}</div><div class="muted">ID: ${esc(e.evidence_id)}</div><div>${safeUrl(e.url)?`<a href="${esc(e.url)}" target="_blank" rel="noreferrer">${esc(e.title)}</a>`:esc(e.title)}</div><div class="muted">${esc((e.text||'').slice(0,500))}</div></div>`).join(''):'<div class="empty">No evidence</div>';
  byId('drawer').classList.add('open');byId('detailTitle').textContent=d.title;byId('detailMeta').textContent=`${d.stage} · Score ${d.score} · Risk ${d.risk_score} · Evidence ${d.evidence_count}`;
  const conflictHtml=conflict.status?`<div class="muted">Policy: ${esc(conflict.selection_policy)} · Selected: ${esc(conflict.selected_provider_id)} · Providers: ${esc(conflict.provider_count)}</div><div class="${conflict.status==='CONFLICT'?'warn':'ok'}">${esc(conflict.status)}${conflict.conflicting_fields?.length?` · fields: ${esc(conflict.conflicting_fields.join(', '))}`:''}</div>`:'<div class="muted">Single-provider result; no conflict report</div>';
  byId('detailBody').innerHTML=`<div class="panel"><h2>Research state</h2><div class="form-grid"><select id="researchStatus" class="field"><option>NEW</option><option>REVIEWING</option><option>TRACKING</option><option>DISMISSED</option><option>ARCHIVED</option></select><select id="researchPriority" class="field">${[0,1,2,3,4,5].map(v=>`<option value="${v}">P${v}</option>`).join('')}</select><label><input id="researchStar" type="checkbox"> Starred</label><input id="researchTags" class="field" placeholder="Tags, comma separated" value="${esc((r.tags||[]).join(','))}"><textarea id="researchNotes" class="field full" placeholder="Research notes">${esc(r.notes||'')}</textarea>${canWrite()?`<button class="btn primary full" data-action="save-research" data-id="${id}">Save research state</button>`:`<div class="muted full">Read-only role cannot update research state</div>`}</div></div><div class="panel"><h2>Structured analysis</h2><p><b>Summary</b><br>${esc(analysis.summary)}</p><p><b>Target user</b><br>${esc(analysis.target_user)}</p><p><b>Business model</b><br>${esc(analysis.business_model)}</p><p><b>Monetization</b><br>${esc(analysis.monetization)}</p><p><b>Risk</b><br>${esc(analysis.risk_notes)}</p></div><div class="panel"><h2>Provider selection</h2>${conflictHtml}</div><div class="panel"><h2>Analysis citations</h2><div class="muted">Contract v${esc(analysis.citation_contract_version||d.evidence_contract?.version||'')}</div><div class="${citationStatus==='Citation bindings verified'?'ok':'bad'}">${citationStatus}</div>${citationHtml}</div><div class="panel"><h2>Keywords</h2>${(d.keywords||[]).map((k:any)=>`<span class="tag">${esc(k.keyword)} · ${esc(k.role)}</span>`).join('')}</div><div class="panel"><h2>Evidence chain</h2>${evidenceHtml}</div>`;
  byId('researchStatus').value=r.status;byId('researchPriority').value=String(r.priority);byId('researchStar').checked=!!r.starred;
}
function closeDrawer(){byId('drawer').classList.remove('open')}
async function saveResearch(id: number){await guard(async()=>{await api(`/api/v1/opportunities/${id}/research`,{method:'PATCH',body:JSON.stringify({status:byId('researchStatus').value,starred:byId('researchStar').checked,priority:Number(byId('researchPriority').value),notes:byId('researchNotes').value,tags:byId('researchTags').value.split(',').map((x:string)=>x.trim()).filter(Boolean)})});await openOpportunity(id);await loadOpportunities()})}

async function loadAlerts(){const [rules,events]=await Promise.all([api('/api/v1/alerts/rules'),api('/api/v1/alerts/events?limit=200')]);byId('ruleList').innerHTML=rules.length?rules.map((r:any)=>`<div class="evidence"><b>${esc(r.name)}</b> · ${r.enabled?'启用':'停用'}<div class="muted">score ≥ ${esc(r.min_score)} · risk ≤ ${esc(r.max_risk_score)} · evidence ≥ ${esc(r.min_evidence_count)} ${r.keyword_contains?.length?'· '+esc(r.keyword_contains.join(',')):''}</div></div>`).join(''):'<div class="empty">暂无规则</div>';byId('alertRows').innerHTML=events.length?events.map((e:any)=>`<tr class="clickable" data-action="open-opportunity" data-id="${e.opportunity_id}"><td>${fmt(e.created_at)}</td><td>${esc(e.title)}</td><td>${esc(e.score)}</td><td>${esc(e.status)}</td><td>${e.status==='NEW'&&canWrite()?`<button class="btn" data-action="ack-alert" data-id="${e.id}">确认</button>`:''}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">暂无预警</td></tr>'}
async function createRule(){await guard(async()=>{await api('/api/v1/alerts/rules',{method:'POST',body:JSON.stringify({name:byId('ruleName').value.trim(),min_score:Number(byId('ruleScore').value||60),max_risk_score:Number(byId('ruleRisk').value||100),min_evidence_count:2,keyword_contains:byId('ruleKeywords').value.split(',').map((x:string)=>x.trim()).filter(Boolean)})});byId('ruleName').value='';await loadAlertsWithLifecycle()})}
async function evaluateAlerts(){await guard(async()=>{await api('/api/v1/alerts/evaluate',{method:'POST'});await loadAlertsWithLifecycle();await loadDashboard()})}
async function ackAlert(id: number){await updateAlertStatus(id,'ACKNOWLEDGED')}

async function loadWatch(){const rows=await api('/api/v1/watch-keywords');byId('watchRows').innerHTML=rows.length?rows.map((r:any)=>`<tr><td>${esc(r.keyword)}</td><td>P${esc(r.priority)}</td><td>${r.enabled?'启用':'暂停'}</td><td>${esc(r.notes)}</td><td>${canWrite()?`<button class="btn" data-action="toggle-watch" data-id="${r.id}" data-enabled="${!r.enabled}">${r.enabled?'暂停':'启用'}</button>`:'<span class="muted">只读</span>'}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">暂无主动关注词</td></tr>'}
async function addWatch(){await guard(async()=>{await api('/api/v1/watch-keywords',{method:'POST',body:JSON.stringify({keyword:byId('watchKeyword').value.trim(),priority:Number(byId('watchPriority').value)})});byId('watchKeyword').value='';await loadWatch()})}
async function toggleWatch(id: number,enabled: boolean){await guard(async()=>{await api(`/api/v1/watch-keywords/${id}`,{method:'PATCH',body:JSON.stringify({enabled})});await loadWatch()})}
async function syncProbes(){await guard(async()=>{await api('/api/v1/probes/sync',{method:'POST'});if(byId('operations').classList.contains('active'))await loadOperations()})}

async function loadSources(){const [sources,health]=await Promise.all([api('/api/v1/sources'),api('/api/v1/sources/health')]);const hm=Object.fromEntries(health.map((h:any)=>[h.source_id,h]));byId('sourceRows').innerHTML=sources.map((s:any)=>{const h=hm[s.source_id]||{};return `<tr><td>${esc(s.display_name)}<div class="muted">${esc(s.source_id)}</div></td><td>${esc(s.acquisition_method)}</td><td>${esc(s.evidence_quality)}</td><td>${esc(s.query_mode)}</td><td><span class="status-dot ${s.runtime_enabled?'on':'off'}"></span>${s.runtime_enabled?'启用':'停用'}</td><td>${esc(h.status||'UNKNOWN')}<div class="muted">runs ${esc(h.total_runs||0)} / fail ${esc(h.failed_runs||0)}</div></td><td><input id="note_${esc(s.source_id)}" class="field" value="${esc(s.preference_note||'')}"></td><td>${isAdmin()?`<button class="btn" data-action="save-source" data-source-id="${esc(s.source_id)}" data-enabled="${!s.runtime_enabled}">${s.runtime_enabled?'停用':'启用'}</button>`:'<span class="muted">只读</span>'}</td></tr>`}).join('')}
async function saveSource(id: string,enabled: boolean){await guard(async()=>{await api(`/api/v1/sources/${encodeURIComponent(id)}/preference`,{method:'PATCH',body:JSON.stringify({enabled,note:byId(`note_${id}`).value})});await loadSources()})}

let observationCursor: string|null = null;
async function loadObservations(append=false){
  const p=new URLSearchParams({limit:'200'});const q=byId('obsQ').value.trim();const source=byId('obsSource').value.trim();if(q)p.set('q',q);if(source)p.set('source_id',source);if(append&&observationCursor)p.set('cursor',observationCursor);
  const d=await api('/api/v1/observations?'+p);byId('obsCount').textContent=`共 ${d.total} 条，当前批次 ${d.items.length} 条`;const html=d.items.map((x:any)=>`<tr><td>${fmt(x.observed_at)}</td><td>${esc(x.source_id)}</td><td>${esc(x.item_type)}</td><td>${esc(x.query)}</td><td>${safeUrl(x.source_url)?`<a href="${esc(x.source_url)}" target="_blank" rel="noreferrer">${esc(x.title)}</a>`:esc(x.title)}</td><td>${esc(x.evidence_quality)} / ${esc(x.acquisition_method)}</td></tr>`).join('');if(append)byId('obsRows').insertAdjacentHTML('beforeend',html);else byId('obsRows').innerHTML=html;observationCursor=d.next_cursor||null;byId('obsMore').style.display=observationCursor?'':'none';
}


async function loadUsers(){if(!isAdmin())return;const rows=await api('/api/v1/admin/users');const roleOptions=(current:string)=>['VIEWER','RESEARCHER','ADMIN','OWNER'].map(role=>`<option value="${role}" ${role===current?'selected':''} ${role==='OWNER'&&!isOwner()?'disabled':''}>${role}</option>`).join('');byId('userRows').innerHTML=rows.length?rows.map((u:any)=>{const protectedOwner=u.role==='OWNER'&&!isOwner();return `<tr><td>${esc(u.username)}</td><td>${protectedOwner?'<span class="pill">OWNER</span>':`<select id="userRole_${u.id}" class="field">${roleOptions(u.role)}</select>`}</td><td>${protectedOwner?esc(u.enabled?'启用':'停用'):`<select id="userEnabled_${u.id}" class="field"><option value="true" ${u.enabled?'selected':''}>启用</option><option value="false" ${!u.enabled?'selected':''}>停用</option></select>`}</td><td>${fmt(u.last_login_at)}</td><td>${u.locked_until?fmt(u.locked_until):''}</td><td>${protectedOwner?'—':`<input id="userPassword_${u.id}" class="field" type="password" autocomplete="new-password" placeholder="留空不修改">`}</td><td>${protectedOwner?'<span class="muted">仅 OWNER 可管理</span>':`<button class="btn" data-action="save-user" data-id="${u.id}">保存</button>`}</td></tr>`}).join(''):'<tr><td colspan="7" class="empty">暂无用户</td></tr>'}
async function saveUser(id:number){await guard(async()=>{if(!isAdmin())throw new Error('需要 ADMIN 权限');const role=byId(`userRole_${id}`).value;const enabled=byId(`userEnabled_${id}`).value==='true';const password=byId(`userPassword_${id}`).value;const payload:any={role,enabled};if(password)payload.password=password;await api(`/api/v1/admin/users/${id}`,{method:'PATCH',body:JSON.stringify(payload)});await loadUsers()})}
async function createUser(){await guard(async()=>{if(!isAdmin())throw new Error('需要 ADMIN 权限');const username=byId('newUsername').value.trim();const password=byId('newPassword').value;const role=byId('newRole').value;await api('/api/v1/admin/users',{method:'POST',body:JSON.stringify({username,password,role,enabled:true})});byId('newUsername').value='';byId('newPassword').value='';await loadUsers()})}

async function loadOperations(){const [tasks,runs,audit,workers]=await Promise.all([api('/api/v1/probes/tasks?limit=300'),api('/api/v1/collection-runs?limit=200'),api('/api/v1/audit?limit=200'),api('/api/v1/workers')]);byId('probeRows').innerHTML=tasks.map((x:any)=>`<tr><td>${esc(x.source_id)}</td><td>${esc(x.query)}</td><td>${esc(x.intent)}</td><td>${fmt(x.next_run_at)}</td><td>${x.active?'ACTIVE':'PAUSED'} ${esc(x.last_status||'')}</td></tr>`).join('');byId('runRows').innerHTML=runs.map((x:any)=>`<tr><td>${fmt(x.started_at)}</td><td>${esc(x.source_id)}</td><td>${esc(x.query)}</td><td>${esc(x.worker_id||'')}</td><td>${esc(x.status)}</td><td>${esc(x.duration_ms??'')} ms</td></tr>`).join('');byId('workerRows').innerHTML=workers.length?workers.map((x:any)=>`<tr><td>${esc(x.worker_id)}</td><td>${esc(x.mode)}</td><td>${esc(x.status)}</td><td>${fmt(x.last_seen_at)}</td><td>${esc(x.iteration_count)}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">暂无 Worker 心跳</td></tr>';byId('auditRows').innerHTML=audit.map((x:any)=>`<tr><td>${fmt(x.created_at)}</td><td>${esc(x.actor)}</td><td>${esc(x.action)}</td><td>${esc(x.resource)}</td><td>${esc(x.status_code)}</td><td class="muted">${esc(x.request_id)}</td></tr>`).join('')}
async function previewRetention(){await guard(async()=>{const d=await api('/api/v1/maintenance/retention?dry_run=true',{method:'POST'});byId('retentionInfo').textContent=(Object.entries(d.policies) as any[]).map(([k,v])=>`${k}: ${v.enabled?`${v.eligible} eligible${v.protected?' (protected)':''}`:'disabled'}`).join(' · ')})}
async function generateDailyDigest(){await guard(async()=>{await api('/api/v1/digests/daily/generate',{method:'POST'});await loadDashboard()})}
async function generateWeeklyTrends(){await guard(async()=>{await api('/api/v1/trends/weekly/generate',{method:'POST'});await loadDashboard()})}

async function login(){await guard(async()=>{const username=(byId('loginUsername') as HTMLInputElement).value.trim();const password=(byId('loginPassword') as HTMLInputElement).value;await loginRequest(username,password);(byId('loginPassword') as HTMLInputElement).value='';await bootstrap();})}
async function logout(){await guard(async()=>{await logoutRequest();await bootstrap();})}
function setAuthenticatedUi(authenticated:boolean,label:string){const loginPanel=byId('loginPanel')!;const appShell=byId('appViews')!;loginPanel.style.display=authenticated?'none':'block';appShell.style.display=authenticated?'block':'none';byId('currentUser')!.textContent=label;applyRoleUi();}
async function bootstrap(){const cfg=await getAuthConfig();setCsrfCookieName(cfg.csrf_cookie_name||'or_csrf');if(PERMISSION_MATRIX_VERSION!=='rbac-v1')throw new Error('unsupported permission matrix');if(cfg.auth_mode==='rbac'){try{const me=await api('/api/v1/auth/me');currentRole=me.role||'VIEWER';setAuthenticatedUi(true,`${me.user?.username||me.actor} · ${me.role}`);}catch{currentRole='VIEWER';setAuthenticatedUi(false,'未登录');return}}else{currentRole='OWNER';setAuthenticatedUi(true,cfg.auth_mode==='disabled'?'开发模式':'API 鉴权模式')}const requested=(location.hash||'#dashboard').slice(1);const initial=allowedView(requested)?requested:'dashboard';showView(document.getElementById(initial)?initial:'dashboard');}

document.addEventListener("click",(event)=>{const target=(event.target as HTMLElement).closest<HTMLElement>("[data-action]");if(!target)return;const action=target.dataset.action;event.preventDefault();if(action==="login")void login();else if(action==="logout")void logout();else if(action==="refresh")refreshCurrent();else if(action==="load-opportunities"){opportunityCursor=null;void loadOpportunities(false);}else if(action==="load-more-opportunities")void loadOpportunities(true);else if(action==="export")void guard(()=>downloadExport(target.dataset.url||"",target.dataset.filename||"export.csv"));else if(action==="create-rule")void createRule();else if(action==="evaluate-alerts")void evaluateAlerts();else if(action==="add-watch")void addWatch();else if(action==="sync-probes")void syncProbes();else if(action==="load-observations"){observationCursor=null;void loadObservations(false);}else if(action==="load-more-observations")void loadObservations(true);else if(action==="preview-retention")void previewRetention();else if(action==="generate-digest")void generateDailyDigest();else if(action==="generate-weekly")void generateWeeklyTrends();else if(action==="create-user")void createUser();else if(action==="save-user")void saveUser(Number(target.dataset.id));else if(action==="close-drawer")closeDrawer();else if(action==="open-opportunity")void openOpportunity(Number(target.dataset.id));else if(action==="save-research")void saveResearch(Number(target.dataset.id));else if(action==="ack-alert"){event.stopPropagation();void ackAlert(Number(target.dataset.id));}else if(action==="toggle-watch")void toggleWatch(Number(target.dataset.id),target.dataset.enabled==="true");else if(action==="save-source")void saveSource(target.dataset.sourceId||"",target.dataset.enabled==="true");});

Object.assign(window,{showView,refreshCurrent,openOpportunity,closeDrawer,saveResearch,createRule,evaluateAlerts,ackAlert,addWatch,toggleWatch,syncProbes,saveSource,loadObservations,previewRetention,generateDailyDigest,generateWeeklyTrends,createUser,saveUser,downloadExport,login,logout});
function alertActions(event:any){if(!canWrite())return '';if(event.status==='NEW')return `<button class="btn" data-action="alert-status" data-status="ACKNOWLEDGED" data-id="${event.id}">Acknowledge</button> <button class="btn" data-action="alert-status" data-status="DISMISSED" data-id="${event.id}">Dismiss</button>`;if(event.status==='ACKNOWLEDGED')return `<button class="btn" data-action="alert-status" data-status="RESOLVED" data-id="${event.id}">Resolve</button> <button class="btn" data-action="alert-status" data-status="DISMISSED" data-id="${event.id}">Dismiss</button>`;return '';}
async function updateAlertStatus(id:number,status:string){await guard(async()=>{await api(`/api/v1/alerts/events/${id}`,{method:'PATCH',body:JSON.stringify({status})});await loadAlertsWithLifecycle()})}
async function loadAlertsWithLifecycle(){const [rules,events]=await Promise.all([api('/api/v1/alerts/rules'),api('/api/v1/alerts/events?limit=200')]);byId('ruleList').innerHTML=rules.length?rules.map((r:any)=>`<div class="evidence"><b>${esc(r.name)}</b> · ${r.enabled?'enabled':'disabled'}<div class="muted">score ≥ ${esc(r.min_score)} · risk ≤ ${esc(r.max_risk_score)} · evidence ≥ ${esc(r.min_evidence_count)}</div></div>`).join(''):'<div class="empty">No alert rules</div>';const header=byId('alertRows').closest('table')?.querySelector('thead tr');if(header&&header.children.length===5)header.children[3].insertAdjacentHTML('beforebegin','<th>Priority</th>');byId('alertRows').innerHTML=events.length?events.map((e:any)=>{const row=e.opportunity_id?` class="clickable" data-action="open-opportunity" data-id="${e.opportunity_id}"`:'';return `<tr${row}><td>${fmt(e.created_at)}</td><td>${esc(e.title)}${e.keyword_id?`<div class="muted">keyword #${esc(e.keyword_id)}</div>`:''}${e.tool_product_entity_id?`<div class="muted">tool/product entity #${esc(e.tool_product_entity_id)}</div>`:''}</td><td>${esc(e.score)}</td><td>P${esc(e.priority??1)}</td><td>${esc(e.status)}</td><td>${alertActions(e)}</td></tr>`}).join(''):'<tr><td colspan="6" class="empty">No alert events</td></tr>'}
Object.assign(window,{updateAlertStatus});
void bootstrap();
document.addEventListener("click",(event)=>{const target=(event.target as HTMLElement).closest<HTMLElement>("[data-action='alert-status']");if(!target)return;event.preventDefault();event.stopPropagation();void updateAlertStatus(Number(target.dataset.id),target.dataset.status||'');});
document.addEventListener("click",(event)=>{const target=(event.target as HTMLElement).closest<HTMLElement>("[data-action='open-opportunity']");if(!target)return;event.stopImmediatePropagation();void openOpportunityWithCitations(Number(target.dataset.id));});
